### ISSUE TITLE
Commit messages

### ISSUE THREAD

**Issue by leucos** [urbanlab/griotte#5]
Les commits messages servent vraiment à quelquechose.
Commiter avec un 'ok' comme message ça ne donne pas vraiment d'information sur ce à quoi a servi le commit.

http://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message

Un petit effort là dessus serait le bienvenu...

**Comment by Maigre** [comment]
Effectivement :+1: 
Par contre les labels des issues Github servent également à quelque chose, et cette remarque n'est pas un "bug" ! attention donc d'appliquer les bonnes pratiques jusqu'au bout :)

**Comment by leucos** [comment]
Mieux ?

**Comment by Maigre** [comment]
:+1:
